### ISSUE TITLE
Running out cards in the deck causes a runtime error.

### ISSUE THREAD

**Issue by nickfang** [nickfang/go-solitaire#13]
It looks like we don't handle the case where the last card on the deck is put somewhere like the board or the stacks.

```
0   2♥ 1
ds
     [  9♠  2♥  4♣  8♦]
  K♥  K♠  K♣  Q♠  3♥  8♣  K♦
  Q♣  Q♦  Q♥  J♥      7♥    
  J♦  J♠  J♣ 10♣      6♣    
 10♠ 10♥ 10♦  9♥      5♥    
  9♦  9♣                    
      8♥                    
      7♣                    
      6♥                    
      5♣                    
      4♥                    
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
solitaire/game.Game.getCurrentCard(...)
	/Users/nfang/workspace/go-solitaire/game/game.go:34
solitaire/game.Game.DisplayCurrentCard(...)
	/Users/nfang/workspace/go-solitaire/game/game.go:297
solitaire/game.Game.DisplayCards({{0xc0000c7700, 0x0, 0x24}, {0xc0000ba240, 0x7, 0x8}, {0xc0000b82a0, 0x4, 0x4}, 0x0, ...})
	/Users/nfang/workspace/go-solitaire/game/game.go:301 +0x187
solitaire/game.Game.Display({{0xc0000c7700, 0x0, 0x24}, {0xc0000ba240, 0x7, 0x8}, {0xc0000b82a0, 0x4, 0x4}, 0x0, ...})
	/Users/nfang/workspace/go-solitaire/game/game.go:307 +0x7a
main.main()
	/Users/nfang/workspace/go-solitaire/main.go:72 +0xd78
exit status 2

**Comment by nickfang** [comment]
fixed in main
